/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _edit_screen_4_h_
#define _edit_screen_4_h_
//---------------------------------------------------------------------------------
extern const unsigned char edit_screen_4[];
extern const int edit_screen_4_size;
//---------------------------------------------------------------------------------
#endif //_edit_screen_4_h_
//---------------------------------------------------------------------------------
