/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _highlight_h_
#define _highlight_h_
//---------------------------------------------------------------------------------
extern const unsigned char highlight[];
extern const int highlight_size;
//---------------------------------------------------------------------------------
#endif //_highlight_h_
//---------------------------------------------------------------------------------
