/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _main_screen_h_
#define _main_screen_h_
//---------------------------------------------------------------------------------
extern const unsigned char main_screen[];
extern const int main_screen_size;
//---------------------------------------------------------------------------------
#endif //_main_screen_h_
//---------------------------------------------------------------------------------
