/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _send_screen_h_
#define _send_screen_h_
//---------------------------------------------------------------------------------
extern const unsigned char send_screen[];
extern const int send_screen_size;
//---------------------------------------------------------------------------------
#endif //_send_screen_h_
//---------------------------------------------------------------------------------
